CREATE TABLE inventory (
  id INT PRIMARY KEY AUTO_INCREMENT,
  item_name VARCHAR(50) NOT NULL,
  quantity INT NOT NULL,
  description VARCHAR(255),
  price DECIMAL(10, 2) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);